config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  use_doorkeeper

  resources :inbound_emails, only: [:create]
  resources :chat_threads
  resources :chat_messages
  
  namespace :api do
    namespace :v1 do
      Seahorse::Model.add_all_routes(self, exclude_rpc_routes: true)
    end
  end

  mount Api::Base => '/api'
  
  root :to => "home#index", :constraints => LoggedInConstraint.new(:logged_out_route)
  root :to => "recognitions#index", :constraints => LoggedInConstraint.new(:logged_in_route), as: :authenticated_root

  get '/proxy.html' => "home#proxy"
  
  # MISC ROUTES
  resources :password_resets, except: [:destroy]
  resources :support_emails, only: [:new, :create]

  get '/contact', to: 'support_emails#new', as: :contact
  get '/sales', to: 'support_emails#sales', as: :contact_sales

  # FILE ROUTES
  get '/extensions/recognize.xpi', to: 'files#firefox_extension'

  #ADMIN ROUTES
  get '/admin', to: 'admin/index#index', as: :admin, via: :get

  namespace :admin do
    get 'emails' => 'index#emails'
    get 'email' => 'index#email'
    get 'signup_requests' => 'index#signup_requests'
    get 'login' => "index#login"
    get 'graph' => 'index#graph'
    get 'paid_engagement' => 'index#paid_engagement'
    get 'analytics' => "index#analytics"
    post 'refresh_analytics' => "index#refresh_analytics"
    get 'queue' => "index#queue"
    post 'purge_failed_queue' => "index#purge_failed_queue"
    
    get '/login_as', to: "index#login_as"
    post "/login_as", to: "index#login_as"
    post '/clear_queue_task/:task', to: "index#clear_queue_task", as: :clear_queue_task

    # match '/enable_custom_badges' => 'index#enable_custom_badges', via: [:post]
    # get 'manage'
    resources :companies, only: [:show, :create], constraints: {:id => /[^\/]+/}  do
      member do
        post "enable_custom_badges"
        post "enable_admin_dashboard"
        post "enable_achievements"
        post "enable_theme"
        patch :add_users
        post :add_directors
        delete :remove_directors
      end
      resources :subscriptions, except: [:index] do
        member do
          patch :cancel
        end
      end
    end

    resources :recognitions, only: [:index]

    resources :users, only: [:index] do 
      collection do 
        get :search
      end
    end

    resources :badges, only: [:index, :show]
    resources :subscriptions, only: [:index]
    resources :coupons do
      collection do
        post :sync
      end
    end
  end
  
  #SESSION ROUTES
  get '/ping', to: 'user_sessions#ping'
  get '/login', to: 'user_sessions#new'
  get '/login/signin', to: 'user_sessions#create', :as => :signin, :id => 'Sign In'
  get '/logout', to: 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  
  #AUTHENTICATION ROUTES
  get '/auth/failure', to: 'authentications#failure', :as => :auth_failure
  get '/auth/:provider', to: 'authentications#create', :as => :remote_auth
  get '/auth/:provider/callback', to: 'authentications#create'

  # STATIC PATHS
  get "/getting-started", to: "home#getting_started", as: :getting_started
  get '/gamification', to: "home#gamification", as: :gamification
  get '/best-recognition-contest-2014', to: "home#contest", as: :contest
  get '/goto', to: "users#goto"
  get '/resend_verification_email', to: "password_resets#new", as: :resend_verification_email
  get '/home', to: "home#index", as: :marketing
  get '/sign-up', to: "home#sign_up", as: :sign_up
  get '/tour', to: "home#tour", as: :tour
  get '/engagement', to: "home#engagement", as: :engagement
  get '/analytics', to: "home#analytics", as: :analytics
  get '/customizations', to: "home#customizations", as: :customizations
  get '/pricing', to: "home#pricing", as: :pricing
  get '/features', to: "home#features", as: :features
  get '/about', to: "home#about", as: :about
  get '/yammer-integration', to: "home#extension", as: :extension
  get '/why-employee-recognition', to: "home#why", as: :why
  get '/case-study',to: "home#case_study", as: :case_study
  get '/privacy', to: "home#privacy_policy", as: :privacy_policy
  get '/terms', to: "home#terms_of_use", as: :terms_of_use
  get '/maintenance', to: "home#maintenance", :as => :maintenance
  get '/coworkers', to: "users#coworkers", as: :coworkers
  get '/help', to: redirect("http://recognize.zendesk.com"), :as => :help
  get '/upgrade/(:code)', to: "home#upgrade", as: :upgrade_promotion
  get "/distributed-workforce-infographic", to: "home#distributed_workforce_infographic", as: :distributed_workforce_infographic
  get "/year-in-review", to: "mailers#year_in_review"  
  get "/unsubscribe/:token", to: "users#unsubscribe", as: :unsubscribe
  get "/rewards", to: "home#rewards", as: :rewards
  get "/employee-recognition-awards", to: "home#awards", as: "awards"
  get "/office-365", to: "home#office365", as: :office365
  get "/mobile-employee-recognition", to: "home#mobile", as: :mobile
  get "/idp_check", to: "saml#idp_check"

  # COMPANY SCOPED ROUTES
  scope "/:network", constraints: {:network => /[^\/]+/} do
    constraints DomainConstraint.new do
      get "/" => "recognitions#index", as: "stream"
      get '/welcome', to: 'welcome#show', as: "welcome"
      put '/welcome/save_user_count', to: 'welcome#save_user_count', as: :save_user_count
  
      resources :subscriptions
      get '/upgrade', to: "subscriptions#new", as: :upgrade  
      get '/upgrade/(:code)', to: "subscriptions#new"

      # CORE RESOURCE ROUTES
      resource :company, only: [:show, :update] do
        resources :badges, only: [:new, :create, :destroy, :index, :show] do
          collection do
            patch :update_all
          end
        end

        get :accounts
        get :check_list
        get :reports
        get :recognitions
        post :update_privacy
        post :update_settings
        put :add_users
        post :resend_invitation_email
        patch :update_point_values
        patch :update_kiosk_mode_key
        patch :update_recognition_limits

        resources :rewards
        resource :saml_configuration

      end

      scope :company, module: :company_admin, as: :company_admin do
        resources :roles
        resources :nominations, only: [:index] do
          member do
            get :votes
            post :award
          end
        end
        resources :campaigns, only: [:show] do
          member do 
            post :archive
          end
        end
      end

      resources :departments
      resources :hall_of_fame
      resource :accounts, only: [:edit, :update]
      resources :redemptions, path: 'rewards'

      resources :teams do
        scope module: 'team_management' do
          resource :members, only: [:edit, :update]
          resource :managers, only: [:edit, :update]          
        end
        member do 
          get :nominations          
        end
      end

      resource :team_assignment, only: [:create, :destroy]

      resource :anniversaries , only: [] do
        collection do
          get :change_roles
          get :assign_role
          get :unassign_role
          get :add_user
          get :remove_user
        end
      end

      resources :email_settings
      # resources :invite

      #REPORTS ROUTES
      get "/reports", to: "reports#index", as: :reports
      get "/reports/users", to: "reports#users", as: :user_reports
      get "/reports/teams", to: "reports#teams", as: :team_reports
      get "/reports/top_users", to: "reports#top_users", as: :top_users_reports
      # get "/reports/:start_date", to: "reports#previous", as: :previous_report
      # get "/reports/badge/:badge_id/:start_date", to: "reports#badge_leaderboard", as: :badge_leaderboard

      # RECOGNITION ROUTES
      # skip show since that needs to be accessed unscoped
      # NOTE: must be above users to avoid dynamic matching
      resources :recognitions, except: [:show, :update, :destroy, :badge] do
        collection do
          post :recognize_instantly
          get :new_chromeless
        end
        member do
          patch :update, as: "update"
          delete :destroy, as: "destroy"
          put :toggle_privacy
        end
        resources :approvals, controller: "recognition_approvals", only: [:create, :destroy]
      end

      resource :identity_provider, path: "idp", only: [:show]
      resources :nominations, only: [:index, :new, :create] do
        collection do
          get :new_chromeless
        end
      end

      # USER ROUTES
      get "/users", to: "users#index", as: "users"
      resources :users, path: "", path_names: {new: "users/new"}, except:[:index, :create] do
        collection do
          get :invite
          get :get_suggested_yammer_users
          get :get_relevant_yammer_coworkers
          patch :send_invitations      
          patch :invite_from_yammer
        end
        member do
          patch :promote_to_admin
          patch :demote_from_admin
          patch :promote_to_executive
          patch :demote_from_executive
          patch :hide_welcome
          put :has_read_new_feature
          patch :upload_avatar
          patch :update_slug
          patch :revoke_oauth_token
          get :received_recognitions
          get :sent_recognitions
          get :nominations
        end

        # USER RECOGNITION ROUTES
        resources :recognitions, only: [] do
          collection do
            get :sent
            get :received
          end
        end

        resource :company_roles, only: [:create, :destroy], controller: :user_company_roles
      end

      resources :saml, only: :index do
        collection do
          get :sso
          post :acs
          get :metadata
          get :logout
          put :complete
        end
      end      

    end # end constraint
  end # end :domain scope

  # Allow showing a recognition to be unscoped 
  # since param is a guid
  # NOTE: this takes precedence over scoped routes

app/views/user_notifier/_recognition.html.erb
<div style="text-align: center; display: inline-block; width:100%;">
  <%= image_tag badge.permalink(200, "http:"), style: "margin: 10px auto; max-width: 90%;" %>

  <h3 style="<%= mail_styles(:text, :h3) %> font-weight: 600;"><%= badge.short_name %></h3>

  <% if recognition.message.present? %>
    <h2 style="<%= mail_styles(:h2, :text) %>; margin: 10px auto; max-width: 600px;">"<%= recognition.message %>" <span style="<%= mail_styles(:textSubtle) %>"></span></h2>
  <% end%>

  <p style="<%= mail_styles(:text, :p) %>"><%= sender.full_name %> from <%= sender.network %></p>
</div>

app/views/user_notifier/from_template.html.erb
<%= @body.html_safe %>
<% if @sender.email == "josh@recognizeapp.com" %>
<table style="font-family: lato, helvetica, arial, sans-serif;">
  <tbody>
    <tr>
      <td style="vertical-align: top;">
        <img src="https://recognizeapp.com/assets/chrome/logo-mark.png" width=33 height=33 style="margin-right: 3px;">

      </td>
      <td style="vertical-align: top;">
        <h5 style="font-weight: 200; line-height: 15px; color: #333; font-size: 15px; margin: 0 0 3px 0;">Josh Jermaine</h5>
        <h6 style="font-weight: 200; line-height: 15px; margin: 0 0 0 0; color: #adadad; font-size: 15px;">Vice-President of Sales</h6>
      </td>
    </tr>

  </tbody>
</table>

<table style="font-family: lato, helvetica, arial, sans-serif;">
  <tbody>
  <tr>
    <td>
      <p style="margin: 0 0 0px 0; color: #333; font-size: 12px;"><span style="color: #2c79a7; width: 17px; display: inline-block;">m</span> josh@recognizeapp.com</p>
    </td>
    </tr>
    <tr>
    <td>
      <p style="margin: 0 0 0px 0; color: #333; font-size: 12px;"><span style="color: #2c79a7; width: 17px; display: inline-block;">p</span> +1.888.401.8837</p>
    </td>
    </tr>
    <tr>
    <td>
      <p style="margin: 0 0 0 0; color: #333; font-size: 12px;"><span style="color: #2c79a7; width: 17px; display: inline-block;">w</span> https://recognizeapp.com</p>
    </td>
    </tr>
    <tr>
    <td>
      <p style="margin: 0 0 1px 0; color: #333; font-size: 12px;"><span style="color: #2c79a7; width: 17px; display: inline-block;">t</span> @recognizeapp</p>
    </td>
    </tr>
    <tr>
    <td>
      <p style="margin: 0 0 0 0; color: #333; font-size: 12px;"><span style="color: #2c79a7; width: 17px; display: inline-block;">o</span> 479 Jessie St.  <br><span style="margin-left: 20px;"> San Francisco, CA, 94103 USA</span></p>
    </td>
    </tr>
  </tr>
  </tbody>
</table>
<% end %>

app/views/user_notifier/invitation_email.html.erb
<h2 style="<%= mail_styles(:h2, :text, :title) %> padding: 0;"><%= @inviter.full_name%> wants you to join Recognize.</h2>
<p style="<%= mail_styles(:p, :text) %>">Recognize is a social employee recognition and rewards program for <%= @inviter_company.name%>.</p>

<a href="<%= @verification_url %>" style="<%= mail_styles(:button) %> margin-top: 20px; ">Verify your account now</a>

<h3 style="<%= mail_styles(:h3, :text) %>"><strong>Things you want to do:</strong></h3>

<ul>
  <li>
    <a href="<%= edit_user_url(@user) %>" style="<%= mail_styles(:text, :a) %> display: block; margin-bottom: 10px;">Edit your personal information</a>
  </li>
  <li><a href="<%= new_recognition_url(network: @user.network) %>" style="<%= mail_styles(:text, :a) %> display: block; margin-bottom: 10px;">Send a recognition to a colleague</a>
  </li>
  <li><a href="<%= stream_url(network: @user.network) %>" style="<%= mail_styles(:text, :a) %> display: block; margin-bottom: 10px;">See your company's recognitions</a>
  </li>
  <li><a href="<%= extension_url %>" style="<%= mail_styles(:text, :a) %> display: block; margin-bottom: 20px;">Use inside Yammer</a>
  </li>
</ul>

<%= mail_styles(:hr) %><br>

<h3 style="<%= mail_styles(:h3, :text) %>">Gain more from your actions at work.</h3>

<ul style="margin-bottom: 20px;">
  <li style="<%= mail_styles(:p, :text) %>">Official recognition from your colleagues</li>
  <li style="<%= mail_styles(:p, :text) %>">Redeem rewards</li>
  <li style="<%= mail_styles(:p, :text) %>">Celebrate more often</li>
  <li style="<%= mail_styles(:p, :text) %>">Receive awards</li>
</ul>

<a href="<%= @verification_url %>" style="<%= mail_styles(:button) %>">Verify your account now</a>

app/views/user_notifier/invitation_email.text.erb
<%= @inviter.full_name%> wants you to join Recognize.

Recognize is a social employee recognition and rewards program for <%= @inviter_company.name%>.

Verify your account now:
<%= @verification_url %>



Things you want to do:

Edit your personal information
<%= edit_user_url(@user) %>

Send a recognition to a colleague
<%= new_recognition_url(network: @user.network) %>

See your company's recognitions
<%= stream_url(network: @user.network) %>

Use inside Yammer
<%= extension_url %>



Gain more from your actions at work.

+ Official recognition from your colleagues
+ Redeem rewards
+ Celebrate more often
+ Receive awards

Verify your account now:
<%= @verification_url %>

app/views/user_notifier/new_comment.html.erb
<div style="<%= mail_styles(:h2, :text) %>  padding-top:20px; margin-top: 0; margin-bottom: 10px;"><%= @comment.content%></div>
<p style="<%= mail_styles(:textSubtle, :text) %>">- <%= @comment.commenter.full_name %> commented</p>
<br>
<a style="<%= mail_styles(:button) %>" href="<%= recognition_url(@comment.commentable) %>">View the conversation</a>

app/views/user_notifier/password_reset_instructions.html.erb
<h2 style="<%= mail_styles(:h2, :text, :title) %> padding: 0;">Password Reset Link</h2><br>

<a href="<%= @edit_password_reset_url%>" style="<%= mail_styles(:button) %> margin-bottom: 30px;">Click here to reset password</a>

<p style="<%= mail_styles(:p) %>">Email us at <strong class="font-weight: 600;">support@recognizeapp.com</strong> if you need any assistance.</p>

app/views/user_notifier/verification_email.html.erb
<h2 style="<%= mail_styles(:h2, :text, :title) %> padding: 0;">Welcome to Recognize.</h2>

<% if @user.from_inbound_email_id.present? %>
  <p style="<%= mail_styles(:p) %>">We've received your recognition via email. Please take a moment to confirm your account and create a password so we may send out the recognition to your recipients. </p> 

  <a href="<%= @verification_url %>" style="<%= mail_styles(:button) %>">Click here to verify</a>

<% else %>
  <p style="<%= mail_styles(:p) %>">Thanks for signing up with Recognize. Once verified, you can create your recognition profile, send and receive recognitions with your colleagues, and share your recognitions.</p> 
  
  <a href="<%= @verification_url %>" style="<%= mail_styles(:button) %>">Verify email</a>
<% end %>


<h3 style="<%= mail_styles(:text, :h3)%>">Or copy and paste this url:</h3>

<a href="<%= @verification_url %>" style="<%= mail_styles(:text, :a) %>"><%= @verification_url %></a>

app/views/user_notifier/welcome_email.html.erb
<h2 style="<%= mail_styles(:h2, :text, :title) %>We've verified your identity and you are ready for lift off.</h2>

<% if @user.consider_as_contact? %>
  <p style="<%= mail_styles(:p, :text) %>">Look for another email from Josh Jermaine, our head of sales, to help you get started.</p>
<% else %>
  <p style="<%= mail_styles(:p, :text) %>">Others in your company have already joined. Log in now to recognize your coworkers.</p>
<% end %>

<%= link_to "Let's Recognize", login_url, style: "#{mail_styles(:button)}; margin-top: 20px;" %>