config/routes.rb
    post 'refresh_analytics' => "index#refresh_analytics"
    get 'queue' => "index#queue"
    post 'purge_failed_queue' => "index#purge_failed_queue"
    
    get '/login_as', to: "index#login_as"
    post "/login_as", to: "index#login_as"
    post '/clear_queue_task/:task', to: "index#clear_queue_task", as: :clear_queue_task

    # match '/enable_custom_badges' => 'index#enable_custom_badges', via: [:post]
    # get 'manage'
    resources :companies, only: [:show, :create], constraints: {:id => /[^\/]+/}  do
      member do
        post "enable_custom_badges"
        post "enable_admin_dashboard"
        post "enable_achievements"
        post "enable_theme"
        patch :add_users
        post :add_directors
        delete :remove_directors
      end
      resources :subscriptions, except: [:index] do
        member do
          patch :cancel
        end
      end
    end

    resources :recognitions, only: [:index]

    resources :users, only: [:index] do 
      collection do 
        get :search
      end
    end

    resources :badges, only: [:index, :show]
    resources :subscriptions, only: [:index]
    resources :coupons do
      collection do
        post :sync
      end
    end
  end
  
  #SESSION ROUTES
  get '/ping', to: 'user_sessions#ping'
  get '/login', to: 'user_sessions#new'
  get '/login/signin', to: 'user_sessions#create', :as => :signin, :id => 'Sign In'
  get '/logout', to: 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  
  #AUTHENTICATION ROUTES
  get '/auth/failure', to: 'authentications#failure', :as => :auth_failure
  get '/auth/:provider', to: 'authentications#create', :as => :remote_auth
  get '/auth/:provider/callback', to: 'authentications#create'

  # STATIC PATHS
  get "/getting-started", to: "home#getting_started", as: :getting_started
  get '/gamification', to: "home#gamification", as: :gamification
  get '/best-recognition-contest-2014', to: "home#contest", as: :contest
  get '/goto', to: "users#goto"
  get '/resend_verification_email', to: "password_resets#new", as: :resend_verification_email
  get '/home', to: "home#index", as: :marketing
  get '/sign-up', to: "home#sign_up", as: :sign_up
  get '/tour', to: "home#tour", as: :tour
  get '/engagement', to: "home#engagement", as: :engagement
  get '/analytics', to: "home#analytics", as: :analytics
  get '/customizations', to: "home#customizations", as: :customizations
  get '/pricing', to: "home#pricing", as: :pricing
  get '/features', to: "home#features", as: :features
  get '/about', to: "home#about", as: :about
  get '/yammer-integration', to: "home#extension", as: :extension
  get '/why-employee-recognition', to: "home#why", as: :why
  get '/case-study',to: "home#case_study", as: :case_study
  get '/privacy', to: "home#privacy_policy", as: :privacy_policy
  get '/terms', to: "home#terms_of_use", as: :terms_of_use
  get '/maintenance', to: "home#maintenance", :as => :maintenance
  get '/coworkers', to: "users#coworkers", as: :coworkers
  get '/help', to: redirect("http://recognize.zendesk.com"), :as => :help
  get '/upgrade/(:code)', to: "home#upgrade", as: :upgrade_promotion
  get "/distributed-workforce-infographic", to: "home#distributed_workforce_infographic", as: :distributed_workforce_infographic
  get "/year-in-review", to: "mailers#year_in_review"  
  get "/unsubscribe/:token", to: "users#unsubscribe", as: :unsubscribe
  get "/rewards", to: "home#rewards", as: :rewards
  get "/employee-recognition-awards", to: "home#awards", as: "awards"
  get "/office-365", to: "home#office365", as: :office365
  get "/mobile-employee-recognition", to: "home#mobile", as: :mobile
  get "/idp_check", to: "saml#idp_check"

  # COMPANY SCOPED ROUTES
  scope "/:network", constraints: {:network => /[^\/]+/} do
    constraints DomainConstraint.new do
      get "/" => "recognitions#index", as: "stream"
      get '/welcome', to: 'welcome#show', as: "welcome"
      put '/welcome/save_user_count', to: 'welcome#save_user_count', as: :save_user_count
  
      resources :subscriptions
      get '/upgrade', to: "subscriptions#new", as: :upgrade  
      get '/upgrade/(:code)', to: "subscriptions#new"

      # CORE RESOURCE ROUTES
      resource :company, only: [:show, :update] do
        resources :badges, only: [:new, :create, :destroy, :index, :show] do
          collection do
            patch :update_all
          end
        end

        get :accounts
        get :check_list
        get :reports
        get :recognitions
        post :update_privacy
        post :update_settings
        put :add_users
        post :resend_invitation_email
        patch :update_point_values
        patch :update_kiosk_mode_key
        patch :update_recognition_limits

        resources :rewards
        resource :saml_configuration

      end

      scope :company, module: :company_admin, as: :company_admin do
        resources :roles
        resources :nominations, only: [:index] do
          member do
            get :votes
            post :award
          end
        end
        resources :campaigns, only: [:show] do
          member do 
            post :archive
          end
        end
      end

      resources :departments
      resources :hall_of_fame
      resource :accounts, only: [:edit, :update]
      resources :redemptions, path: 'rewards'

      resources :teams do
        scope module: 'team_management' do
          resource :members, only: [:edit, :update]
          resource :managers, only: [:edit, :update]          
        end
        member do 
          get :nominations          
        end
      end

      resource :team_assignment, only: [:create, :destroy]

      resource :anniversaries , only: [] do
        collection do
          get :change_roles
          get :assign_role
          get :unassign_role
          get :add_user
          get :remove_user
        end
      end

      resources :email_settings
      # resources :invite

      #REPORTS ROUTES
      get "/reports", to: "reports#index", as: :reports
      get "/reports/users", to: "reports#users", as: :user_reports
      get "/reports/teams", to: "reports#teams", as: :team_reports
      get "/reports/top_users", to: "reports#top_users", as: :top_users_reports
      # get "/reports/:start_date", to: "reports#previous", as: :previous_report
      # get "/reports/badge/:badge_id/:start_date", to: "reports#badge_leaderboard", as: :badge_leaderboard

      # RECOGNITION ROUTES
      # skip show since that needs to be accessed unscoped
      # NOTE: must be above users to avoid dynamic matching
      resources :recognitions, except: [:show, :update, :destroy, :badge] do
        collection do
          post :recognize_instantly
          get :new_chromeless
        end
        member do
          patch :update, as: "update"
          delete :destroy, as: "destroy"
          put :toggle_privacy
        end
        resources :approvals, controller: "recognition_approvals", only: [:create, :destroy]
      end

      resource :identity_provider, path: "idp", only: [:show]
      resources :nominations, only: [:index, :new, :create] do
        collection do
          get :new_chromeless
        end
      end

      # USER ROUTES
      get "/users", to: "users#index", as: "users"
      resources :users, path: "", path_names: {new: "users/new"}, except:[:index, :create] do
        collection do
          get :invite
          get :get_suggested_yammer_users
          get :get_relevant_yammer_coworkers
          patch :send_invitations      
          patch :invite_from_yammer
        end
        member do
          patch :promote_to_admin
          patch :demote_from_admin
          patch :promote_to_executive
          patch :demote_from_executive
          patch :hide_welcome
          put :has_read_new_feature
          patch :upload_avatar
          patch :update_slug
          patch :revoke_oauth_token
          get :received_recognitions
          get :sent_recognitions
          get :nominations
        end

        # USER RECOGNITION ROUTES
        resources :recognitions, only: [] do
          collection do
            get :sent
            get :received
          end
        end

        resource :company_roles, only: [:create, :destroy], controller: :user_company_roles
      end

      resources :saml, only: :index do
        collection do
          get :sso
          post :acs
          get :metadata
          get :logout
          put :complete
        end
      end      

    end # end constraint
  end # end :domain scope

  # Allow showing a recognition to be unscoped 
  # since param is a guid
  # NOTE: this takes precedence over scoped routes
  #       and thus must be above
  get '/recognitions/:id/share/:provider', to: "recognitions#share", :as => "share_recognition"  
  resources :recognitions, only: [] do
    resources :comments
    member do
      # need to say: recognition_path(@recognition),
      # takes it away from above put/delete resource route
      get :show, as: "" 
      get :certificate, as: 'certificate'

    end
  end
  
  # SIGNUP ROUTES
  resources :signups, path: :signup do
    collection do
      put :full_name
      put :password
      get :confirm_email
      get :requested
      get :recognize
      post :personal_interest
    end
    member do
      get :verify
    end
  end

  resource :account_chooser, controller: :account_chooser, only: [:show, :update]

  # match "/:network/*path", to: "application#routing_error",  constraints: lambda {|request| request.params[:network] != 'uploads'}, format: false
    # match "/:network/*path", to: "application#routing_error", format: false
  # match "*path", to: "application#routing_error"

  get 'robots.txt' => "home#robots"

  get "/:network", to: "application#routing_error", constraints: {:network => /[^\/]+/} , format: false
  get "/:network*path", to: "application#routing_error", constraints: {:network => /[^\/]+/} , format: false

app/models/reward.rb
class Reward < ActiveRecord::Base
  include ActionView::Helpers::UrlHelper

  acts_as_paranoid  
  
  attr_accessible  :title, :description, :points, :company_id, :frequency, :interval_id, :manager_id, :image
  belongs_to :company
  belongs_to :manager, class_name: "User"

  has_many :redemptions, inverse_of: :reward

  validates :title, :description, :points, :manager_id, presence: true
  validates :points, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
  validates :interval_id, inclusion: {in: Interval::RESET_INTERVALS_WITH_NULL.keys}
  validates :frequency, numericality: { only_integer: true, greater_than: 0, allow_blank: true}
  validates :frequency, presence: {message: "can't be blank if interval is specified."}, if: ->{interval_id.present?}
  scope :enabled, ->{ where(enabled: true)}

  mount_uploader :image, AttachmentUploader

  def redeemable_by?(user)
    redeemable = true
    redeemable &&= can_redeem_by_points?
    redeemable &&= can_redeem_within_frequency?(user)
    return redeemable    
  end

  def self.attributes_for_json
    [:id, :title, :description, :company_id, :points, :enabled, :url, :image]
  end

  def url
    Rails.application.routes.url_helpers.company_reward_url(self, network: self.network, host: Recognize::Application.config.host)
  end

  def network
    @network ||= self.company.domain
  end

  def interval
    @interval ||= Interval.new(interval_id)
  end

  def existing_redemptions_count_in_interval(user)
    user.redemptions.where(reward_id: self.id).where("created_at > ?", self.interval.start).size
  end 

  def can_redeem_within_frequency?(user)
    return true if self.interval_id.blank?
    existing_redemptions_count_in_interval(user) < self.frequency
  end

  def can_redeem_by_points?(user)
    user.redeemable_points >= self.points
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @rewards = Reward.enabled.where(company_id: @company.id)
  end

  def create
    company_reward_params = reward_params.merge(:company_id => @company.id) 
    @reward = Reward.new(company_reward_params)
    @reward.save

    if handle_ie_stupidity?
      handle_ie_stupidity

    else
      respond_with @reward
    end

  end

  def update
    @reward = Reward.find(params[:id])
    @reward.update_attributes(reward_params)

    respond_with @reward

  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.update_column(:enabled, false)
  end

  private
  def reward_params
    params.require(:reward).permit(:title, :description, :points, :frequency, :interval_id, :manager_id, :image)
  end

  def handle_ie_stupidity?
    !request.headers["HTTP_ACCEPT"].match(/application\/json|application\/javascript/)
  end

  def handle_ie_stupidity
    request.format = 'json'

    resource = JsonResource.new(@reward, self, [], {})

    status = resource.has_errors? ? 422 : 200
    render :json => resource.to_json, :content_type => "text/plain", status: status

  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
  def link_to_add_reward_card
    new_reward = Reward.new
    id = new_reward.object_id
    form = render("reward_card_form", reward: new_reward)
    link_to("Add Reward", '#', class: "add-reward-card button button-primary", data: {id: id, form: form.gsub("\n", "")})    
  end
end

app/views/rewards/_reward_card_form.html.erb
<div class="reward-card relative widget-box dark">
  <%= form_for [:company, reward], remote: true do |f| %>
    <%= image_tag reward.image.url, class: "reward-image" %>
    <div class="control-group">
      <%= f.label :image, "At least a 250x380 pixel image" %>
      <%= f.file_field :image, :"data-url" => company_rewards_path(network: @company.domain) %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="control-group">
      <%= f.text_field :title, class: "input-xlarge title-input", placeholder: t("rewards.title_of_reward") %>
    </div>

    <div class="control-group">
      <%= f.text_area :description, class: "input-xlarge description-input", placeholder: t("rewards.description_of_reward") %>
    </div>
    <div class="control-group">
      <h5><%= t("rewards.how_many_points") %></h5>
      <%= f.text_field :points, class: "input-xlarge points-input", placeholder: "100" %>
    </div>
    <div class="control-group">
      <h5><%= t("rewards.frequency_and_interval") %></h5>
      <%= f.text_field :frequency, type: :number, placeholder: "10", min: 0, style: "width: 50px;" %>
      <select style="width: 100px;" name="reward[interval_id]">
        <% Interval::RESET_INTERVALS_WITH_NULL.each do |value, name| %>
          <% name = Interval::NULL == value ? "No Limit" : name %>
          <% selected = reward.interval_id == value ? "selected='true'" : "" %>
          <option value="<%= value %>" <%= selected %>><%= name %></option>
        <% end %>
      </select>
    </div>
    <div class="control-group">
      <h5><%= t("rewards.manager") %></h5>
      <%= f.select :manager_id, [[reward.manager.try(:label), reward.manager_id]], {selected: reward.manager_id}, class: "reward-manager-select"%>
    </div>
    <div class="control-group">
      <div class="file-attach-progress">
        <div class="message"></div>
        <div id="progress-bar"><div id="progress-inner"><span class="right"></span></div></div>
      </div>
      <%= f.submit t("dict.save"), class: "button rewards-edit-submit" %>
    </div>
  <% end %>
  <% delete_url = reward.new_record? ? "javascript://" : company_reward_path(reward) %>
  <%= link_to t("dict.delete"), delete_url, class: "close-icon " %>
</div>

app/views/rewards/destroy.js.erb
$(function(){
  $("#edit_reward_<%= @reward.id%>").parents(".reward-card").fadeOut();
})();

app/views/rewards/index.html.erb
<div id="rewards-header-area" class="clearfix">
	<div class="page-main marginBottom10">
		<h2><%=t("rewards.rewards")%></h2>
		<p><%= t("rewards.set_up_rewards")%></p>
	</div>
</div>


<nav class="tab-nav">
  <ul class="clearfix">
    <li class="active"><a href="#rewards-main-area" data-toggle="tab"><%= t("dict.create") %></a></li>
    <li><a href="#rewards-list-area" data-toggle="tab"><%= t("reward.redeemed") %></a></li>
  </ul>
</nav>

<div id="rewards-main-area" class="tab tab-pane active clearfix">
  <nav class="marginBottom30">
    <%= link_to_add_reward_card %>
  </nav>

  <div id="reward-tags-area" class="clearfix">
    <% @rewards.each do |reward|%>
      <%= render "reward_card_form", reward: reward %>
    <%end%>
  </div>
</div>

<div id="rewards-list-area" class="tab tab-pane clearfix">
  <table class="table table-striped table-bordered table-condensed table-hover">
    <th><%= t("dict.user") %></th>
    <th><%= t("dict.date") %></th>
    <th><%= t("reward.reward") %></th>
    <th><%= t("reward.reward_description") %></th>
    <% current_user.company.redemptions.each do |redemption| %>
      <tr>
        <td>
          <%= link_to redemption.user.full_name, user_path(redemption.user) %>
        </td>
        <td>
          <p><%= localize_datetime(redemption.created_at, :friendly_with_time) %></p>
        </td>
        <td>
          <p><%= redemption.reward.title %></p>
        </td>
        <td>
          <p><%= redemption.reward.description %></p>
        </td>
      </tr>
    <% end %>
  </table>

</div>