config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  use_doorkeeper

  resources :inbound_emails, only: [:create]
  resources :chat_threads
  resources :chat_messages
  
  namespace :api do
    namespace :v1 do
      Seahorse::Model.add_all_routes(self, exclude_rpc_routes: true)
    end
  end

  mount Api::Base => '/api'
  
  root :to => "home#index", :constraints => LoggedInConstraint.new(:logged_out_route)
  root :to => "recognitions#index", :constraints => LoggedInConstraint.new(:logged_in_route), as: :authenticated_root

  get '/proxy.html' => "home#proxy"
  
  # MISC ROUTES
  resources :password_resets, except: [:destroy]
  resources :support_emails, only: [:new, :create]

  get '/contact', to: 'support_emails#new', as: :contact
  get '/sales', to: 'support_emails#sales', as: :contact_sales

  # FILE ROUTES
  get '/extensions/recognize.xpi', to: 'files#firefox_extension'

  #ADMIN ROUTES
  get '/admin', to: 'admin/index#index', as: :admin, via: :get

  namespace :admin do
    get 'emails' => 'index#emails'
    get 'email' => 'index#email'
    get 'signup_requests' => 'index#signup_requests'
    get 'login' => "index#login"
    get 'graph' => 'index#graph'
    get 'paid_engagement' => 'index#paid_engagement'
    get 'analytics' => "index#analytics"
    post 'refresh_analytics' => "index#refresh_analytics"
    get 'queue' => "index#queue"
    post 'purge_failed_queue' => "index#purge_failed_queue"
    
    get '/login_as', to: "index#login_as"
    post "/login_as", to: "index#login_as"
    post '/clear_queue_task/:task', to: "index#clear_queue_task", as: :clear_queue_task

    # match '/enable_custom_badges' => 'index#enable_custom_badges', via: [:post]
    # get 'manage'
    resources :companies, only: [:show, :create], constraints: {:id => /[^\/]+/}  do
      member do
        post "enable_custom_badges"
        post "enable_admin_dashboard"
        post "enable_achievements"
        post "enable_theme"
        patch :add_users
        post :add_directors
        delete :remove_directors
      end
      resources :subscriptions, except: [:index] do
        member do
          patch :cancel
        end
      end
    end

    resources :recognitions, only: [:index]

    resources :users, only: [:index] do 
      collection do 
        get :search
      end
    end

    resources :badges, only: [:index, :show]
    resources :subscriptions, only: [:index]
    resources :coupons do
      collection do
        post :sync
      end
    end
  end
  
  #SESSION ROUTES
  get '/ping', to: 'user_sessions#ping'
  get '/login', to: 'user_sessions#new'
  get '/login/signin', to: 'user_sessions#create', :as => :signin, :id => 'Sign In'
  get '/logout', to: 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  
  #AUTHENTICATION ROUTES
  get '/auth/failure', to: 'authentications#failure', :as => :auth_failure
  get '/auth/:provider', to: 'authentications#create', :as => :remote_auth
  get '/auth/:provider/callback', to: 'authentications#create'

  # STATIC PATHS
  get "/getting-started", to: "home#getting_started", as: :getting_started
  get '/gamification', to: "home#gamification", as: :gamification
  get '/best-recognition-contest-2014', to: "home#contest", as: :contest
  get '/goto', to: "users#goto"
  get '/resend_verification_email', to: "password_resets#new", as: :resend_verification_email
  get '/home', to: "home#index", as: :marketing
  get '/sign-up', to: "home#sign_up", as: :sign_up
  get '/tour', to: "home#tour", as: :tour
  get '/engagement', to: "home#engagement", as: :engagement
  get '/analytics', to: "home#analytics", as: :analytics
  get '/customizations', to: "home#customizations", as: :customizations
  get '/pricing', to: "home#pricing", as: :pricing
  get '/features', to: "home#features", as: :features
  get '/about', to: "home#about", as: :about
  get '/yammer-integration', to: "home#extension", as: :extension
  get '/why-employee-recognition', to: "home#why", as: :why
  get '/case-study',to: "home#case_study", as: :case_study
  get '/privacy', to: "home#privacy_policy", as: :privacy_policy
  get '/terms', to: "home#terms_of_use", as: :terms_of_use
  get '/maintenance', to: "home#maintenance", :as => :maintenance
  get '/coworkers', to: "users#coworkers", as: :coworkers
  get '/help', to: redirect("http://recognize.zendesk.com"), :as => :help
  get '/upgrade/(:code)', to: "home#upgrade", as: :upgrade_promotion
  get "/distributed-workforce-infographic", to: "home#distributed_workforce_infographic", as: :distributed_workforce_infographic
  get "/year-in-review", to: "mailers#year_in_review"  
  get "/unsubscribe/:token", to: "users#unsubscribe", as: :unsubscribe
  get "/rewards", to: "home#rewards", as: :rewards
  get "/employee-recognition-awards", to: "home#awards", as: "awards"
  get "/office-365", to: "home#office365", as: :office365
  get "/mobile-employee-recognition", to: "home#mobile", as: :mobile
  get "/idp_check", to: "saml#idp_check"

  # COMPANY SCOPED ROUTES
  scope "/:network", constraints: {:network => /[^\/]+/} do
    constraints DomainConstraint.new do
      get "/" => "recognitions#index", as: "stream"
      get '/welcome', to: 'welcome#show', as: "welcome"
      put '/welcome/save_user_count', to: 'welcome#save_user_count', as: :save_user_count
  
      resources :subscriptions
      get '/upgrade', to: "subscriptions#new", as: :upgrade  
      get '/upgrade/(:code)', to: "subscriptions#new"

      # CORE RESOURCE ROUTES
      resource :company, only: [:show, :update] do
        resources :badges, only: [:new, :create, :destroy, :index, :show] do
          collection do
            patch :update_all
          end
        end

        get :accounts
        get :check_list
        get :reports
        get :recognitions
        post :update_privacy
        post :update_settings
        put :add_users
        post :resend_invitation_email
        patch :update_point_values
        patch :update_kiosk_mode_key
        patch :update_recognition_limits

        resources :rewards
        resource :saml_configuration

      end

      scope :company, module: :company_admin, as: :company_admin do
        resources :roles
        resources :nominations, only: [:index] do
          member do
            get :votes
            post :award
          end
        end
        resources :campaigns, only: [:show] do
          member do 
            post :archive
          end
        end
      end

      resources :departments
      resources :hall_of_fame
      resource :accounts, only: [:edit, :update]
      resources :redemptions, path: 'rewards'

      resources :teams do
        scope module: 'team_management' do
          resource :members, only: [:edit, :update]
          resource :managers, only: [:edit, :update]          
        end
        member do 
          get :nominations          
        end
      end

      resource :team_assignment, only: [:create, :destroy]

      resource :anniversaries , only: [] do
        collection do
          get :change_roles
          get :assign_role
          get :unassign_role
          get :add_user
          get :remove_user
        end
      end

      resources :email_settings
      # resources :invite

      #REPORTS ROUTES
      get "/reports", to: "reports#index", as: :reports
      get "/reports/users", to: "reports#users", as: :user_reports
      get "/reports/teams", to: "reports#teams", as: :team_reports
      get "/reports/top_users", to: "reports#top_users", as: :top_users_reports
      # get "/reports/:start_date", to: "reports#previous", as: :previous_report
      # get "/reports/badge/:badge_id/:start_date", to: "reports#badge_leaderboard", as: :badge_leaderboard

      # RECOGNITION ROUTES
      # skip show since that needs to be accessed unscoped
      # NOTE: must be above users to avoid dynamic matching
      resources :recognitions, except: [:show, :update, :destroy, :badge] do
        collection do
          post :recognize_instantly
          get :new_chromeless
        end
        member do
          patch :update, as: "update"
          delete :destroy, as: "destroy"
          put :toggle_privacy
        end
        resources :approvals, controller: "recognition_approvals", only: [:create, :destroy]
      end

      resource :identity_provider, path: "idp", only: [:show]
      resources :nominations, only: [:index, :new, :create] do
        collection do
          get :new_chromeless
        end
      end

      # USER ROUTES
      get "/users", to: "users#index", as: "users"
      resources :users, path: "", path_names: {new: "users/new"}, except:[:index, :create] do
        collection do
          get :invite
          get :get_suggested_yammer_users
          get :get_relevant_yammer_coworkers
          patch :send_invitations      
          patch :invite_from_yammer
        end
        member do
          patch :promote_to_admin
          patch :demote_from_admin
          patch :promote_to_executive
          patch :demote_from_executive
          patch :hide_welcome
          put :has_read_new_feature
          patch :upload_avatar
          patch :update_slug
          patch :revoke_oauth_token
          get :received_recognitions
          get :sent_recognitions
          get :nominations
        end

        # USER RECOGNITION ROUTES
        resources :recognitions, only: [] do
          collection do
            get :sent
            get :received
          end
        end

        resource :company_roles, only: [:create, :destroy], controller: :user_company_roles
      end

      resources :saml, only: :index do
        collection do
          get :sso
          post :acs
          get :metadata
          get :logout
          put :complete
        end
      end      

    end # end constraint
  end # end :domain scope

  # Allow showing a recognition to be unscoped 
  # since param is a guid
  # NOTE: this takes precedence over scoped routes

app/controllers/home_controller.rb
class HomeController < ApplicationController

  attr_accessor :awards, :rewards, :pricing, :privacy_policy, :analytics,
                :terms_of_use, :contest, :gamification, :engagement,
                :customizations, :getting_started, :office365, :mobile

  def index
    @user_session = UserSession.new
    @support_email = SupportEmail.new
    @support_email.type = params[:type]
    
    #session[:email] may be nil(and probably is) and that's ok
    @user = User.find_or_initialize_by(email: session[:email])

    #the session may contain an email of user that is 
    #all setup and ok to login
    if @user.ok_to_login?
      #if so, then clear out of session and present a new user
      session.delete(:email)
      @user = User.new
    end
    
    @user.company = Company.new unless @user.company 
    
    @pageName = "marketing-home"
  end
  
  def distributed_workforce_infographic
  end

  def tour
    @user = User.new(company: Company.new)
  end

  def sign_up
    if @current_user
      redirect_to root_path
    else
      @user = User.find_or_initialize_by(email: session[:email])
      @user.company = Company.new unless @user.company 
    end
  end

  def features
    @user = User.new(company: Company.new)
  end

  def case_study
    @user = User.new(company: Company.new)
  end

  def about
    @user = User.new(company: Company.new)
  end

  def extension
    @user = User.new(company: Company.new)
  end

  def why
    @user = User.new(company: Company.new)
  end

  #a view of the maintenance page for development
  def maintenance
    render action: "maintenance", layout: false
  end

  def upgrade
    if current_user.present?
      opts = {network: current_user.network}
      opts[:code] = params[:code] if params[:code].present?
      redirect_to upgrade_path(opts)
    else
      flash[:notice] = "Please login to upgrade your account"
      store_location
      redirect_to login_path
    end
  end

  def robots
    render action: "robots", layout: false
  end

  def proxy
    render action: "proxy", layout: false
  end

  protected

  def use_marketing_layout?
    true
  end

  def is_home?
    true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_bottom.html.erb
  <% if current_user.present? %>
    <div class="widget-box-flat">
      <h2>Find out more about Recognize</h2>
      <%= render :partial => "layouts/marketing_links" %>
    </div>
  <% else %>
    <div class="relative">
      <%= render :partial => "email_form", locals: {title: "Add employee recognition to your company's workflow"} %>
    </div>
  <% end %>

app/views/home/_footer.html.erb
<footer class="footer-exp clearfix">
  <div class="inner">
    <ul class="no-bullets">
      <li class="subtext"><a href="http://blog.recognizeapp.com">Blog</a></li>
      <li class="subtext"><a href="http://support.recognizeapp.com">Knowledge &amp; FAQ</a></li>
      <li class="subtext"><a href="/company-engagement-strategy.pdf">HR Philosophy Strategy</a></li>
      <li class="subtext"><a href="/recognize-security-overview.pdf">Security</a></li>
      <li class="subtext"><a href="/terms">Terms of Use</a></li>
      <li class="subtext"><a href="/privacy">Privacy Policy</a></li>
    </ul>

    <ul class="no-bullets" data-no-turbolink='true'>
      <li class="subtext"><%= link_to "Contact Us", contact_sales_path, class: "button button-highlight" %></li>
      <li class="subtext"><a href="mailto:support@recognizeapp.com">Support@recognizeapp.com</a></li>
      <li class="subtext"><a href="mailto:sales@recognizeapp.com">Sales@recognizeapp.com</a></li>

      <li class="subtext">Recognize HQ<br>479 Jessie St.<br>San Francisco, 94103, CA</li>
      <li class="subtext"><a href="tel:8884018837">(888) 401-8837</a></li>
    </ul>

    <p class="subtext">Recognize was created to promote the power of positivity. Our goal is to help companies have excellent company culture through empowerment and motivation. We believe employee recognition and rewards is an intregral part of any company. We will work with all companies of any size to help make that happen. Recognize is a Recognize Services Inc product. </p>
    <p class="marginTop10">
      <a target="_blank" href="https://www.mcafeesecure.com/verify?host=recognizeapp.com"><img class="mfes-trustmark" border="0" src="//cdn.ywxi.net/meter/recognizeapp.com/101.gif" width="125" height="55" title="McAfee SECURE sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" alt="McAfee SECURE sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" oncontextmenu="window.open('https://www.mcafeesecure.com/verify?host=recognizeapp.com'); return false;"></a>
      <!-- End McAfee SECURE Certification Trustmark for recognizeapp.com -->

    </p>
  </div>

</footer>

app/views/home/getting_started.html.erb
<div id="intro-wrapper">
  <h1>Getting Started</h1>
</div>
<%= render :partial => 'footer' %>

app/views/home/index.html.erb
<%= content_for :title, Recognize::Application::SKIP_CONTENT_FOR %>

<%= content_for :pagejs do %>
  <script type="text/javascript">
    if(window.location.hash.indexOf('access_token') >= 0) { window.location = '/auth/yammer';}
  </script>
<% end %>

<div class="exp-wrapper-outer">
  <div class="exp-wrapper">

    <section class="exp-main clearfix home-padding data-no-turbolink="true">
      <div class="inner">
        <div class="exp-top">
          <div class="content">
            <h2>Engaged Companies Use Recognize</h2>
            <p class="tagline balance-text">Social employee recognition and flexible staff rewards.</p>
          </div>

          <div class="centered marginBottom40" data-no-turbolink="true">
            <%= link_to "Sign up", sign_up_path, id: "home-sign-up-top-action", class: "button marginBottom10 button-large button-highlight" %>
            <%= link_to "Request a demo", contact_sales_path, id: "request-demo-top-action", class: "button marginBottom10 button-large button-border" %>
          </div>

          <div class="centered">
            <div id="youtube-video" data-id="2eYHSBUSkcA"></div>
            <%= render partial: "layouts/youtube_load" %>
          </div>
        </div>

      </div>
    </section>

    <section class="testimonial-wrapper home-padding">
      <div class="centered">
        <h2 class="balance-text">What people are solving with Recognize's employee recognition strategy</h2>
      </div>
      <ul class="testimonials clearfix">
        <li>
          <h3 class="balance-text">Run successful customer service campaigns</h3>
          <%= testimonial_html(4) %>
        </li>
        <li>
          <h3 class="balance-text">Automate employee recognition</h3>
          <%= testimonial_html(1) %>
        </li>
        <li>
          <h3 class="balance-text">Increasing Yammer usage through gamification</h3>
          <%= testimonial_html(10) %>
        </li>
        <li>
          <h3 class="balance-text">Focus staff behind company values</h3>
          <%= testimonial_html(7) %>
        </li>
      </ul>
    </section>

    <section class="home-padding value-props-wrapper">
      <div class="inner">
        <div class="centered">
          <h2>Why add social employee recognition &amp; awards to your company</h2>
        </div>
        <%= render partial: "welcome/value_props" %>
      </div>
    </section>


    <section class="exp-buckets home-padding dark">
      <div class="inner">
        <div class="bucket-row clearfix">
          <div class="bucket">
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <span class="rewards-icon"></span>
                <h3>Employee rewards</h3>
              </div>
              <p class="subtext">We offer many types of rewards. Staff can redeem with points at no additional cost. We recommend experiential employee rewards, such as a parking spot, a conference, a half day off, rental of a fancy car, or a pizza party with their team. When employee rewards really show the company cares, you will retain and engage staff.</p>
              <p class="subtext"><%= link_to "Learn more", rewards_path %></p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/ios7-people.png", class: "icon", alt: "People icon" %>
                <h3>Manager &amp; peer-to-peer employee recognition</h3>
              </div>
              <p class="subtext">Recognize made it easy to send and receive official positive feedback for both managers and peers. Create recognition badges only certain people, such as managers or executives, can send to staff. Managers and peers can send employee recognition from the Recognize Chrome extension, Yammer, email, Sharepoint, mobile, Slack, and on any web browser.</p>
            </div>
          </div>
        </div>

        <div class="bucket-row clearfix">
          <div class="bucket">
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <span class="o365-icon"></span>
                <h3>Yammer + Sharepoint for staff recognition and awards</h3>
              </div>
              <p class="subtext">Recognize is the R&amp;R program for Office 365. You can use the entire Recognize platform inside Sharepoint or inside Yammer. Use Recognize's employee engagement strategy within your workflow.</p>
              <p class="subtext"><%= link_to "Learn more", office365_path %></p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/key.png", class: "icon", alt: "key icon" %>
                <h3>Office 365 sign in to Recognize</h3>
              </div>
              <p class="subtext">If your company has Office 365 accounts for your staff, they can login to Recognize automatically. This is true for Office 365, Yammer, Google Apps, and Slack.</p>
              <p class="subtext"><%= link_to "Sign in with Office 365", office365_path %></p>
            </div>
          </div>

        </div>
        <div class="bucket-row clearfix">
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/slack.png", class: "icon", alt: "Slack icon" %>
                <h3>Employee recognition for Slack</h3>
              </div>
              <p class="subtext">Staff can send and receive official employee recognition from Slack. Users do not need to login to start using it. Just have the admin install it as an bot for your company's Slack account. </p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/navigate.png", class: "icon", alt: "navigate icon" %>
                <h3>Employee engagement strategy</h3>
              </div>
              <p class="subtext">Build stronger, happier staff through monthly check-in meetings with Recognize team members. When you sign up for Recognize you not only get the social employee recognition platform, as well as world-class strategy on a monthly basis.</p>
              <p class="subtext"><%= link_to "Best Practices Handbook", "/best-practices-handbook.pdf" %></p>
            </div>
          </div>
        </div>
        <div class="bucket-row clearfix">
          <div class="bucket">
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <span class="settings-icon"></span>
                <h3>Customize employee recognition badges &amp; points</h3>
              </div>
              <p class="subtext">Create a personalized gamification strategy with <strong>badges, leaderboards, points</strong>, and more. You can use one of 30 well-designed badges and change the characteristics of those employee recognition badges. You can also <strong>upload your own badges</strong> in just a couple of clicks. You can change the points associated with a badge or choose who can send a badge.</p>
              <p class="subtext"><%= link_to "Learn more", customizations_path %></p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/ios7-contact.png", class: "icon", alt: "Person icon" %>
                <h3>Employee recognition user management</h3>
              </div>
              <p class="subtext">Recognize supports the popular ActiveDirectory, or LDAP, single sign on for your staff. This is the way to manage users in your company. Recognize can import user spreadsheet, Yammer user data, Slack user data, and Office 365 user data.</p>
            </div>
          </div>
        </div>
        <div class="bucket-row clearfix">
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/podium.png", class: "icon", alt: "Podium icon" %>
                <h3>Staff leaderboards</h3>
              </div>
              <p class="subtext">Customize the leaderboards to focus on the user, teams, or overall throughout your company. The staff leaderboards include filtering by badge or by time.</p>
              <p class="subtext"><%= link_to "View the Recognize engagement", engagement_path %></p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/university.png", class: "icon", alt: "Graduating hat icon" %>
                <h3>Employee award certificates</h3>
              </div>
              <p class="subtext">When a recognition is created, you can print off an employee award certificate that represents that recognition. Certificates can be customized.</p>
              <p class="subtext"><%= link_to "Learn more about employee awards", awards_path %></p>
            </div>
          </div>
        </div>
        <div class="bucket-row clearfix">
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/iphone.png", class: "icon", alt: "iPhone icon" %>
                <h3>Employee recognition mobile apps</h3>
              </div>
              <p class="subtext">Recognize provides mobile-ready employee recognition. Staff and recognition admins can login to the mobile website or soon Android, Windows Phone, and iPhone employee recognition apps.</p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/ios7-chatbubble.png", class: "icon", alt: "chat bubble icon" %>
                <h3>Text message employee recognition</h3>
              </div>
              <p class="subtext">Staff can receive recognition through SMS text message. We help companies set up text message recognition for your entire staff. Your employees won't need to be an existing users.</p>
            </div>
          </div>
        </div>
        <div class="bucket-row clearfix">
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "pages/home-index/exp/trophy.png", class: "icon", alt: "Trophy icon" %>
                <h3>Hall of Fame</h3>
              </div>
              <p class="subtext">Only Recognize offers a visual representation of the top employees across badge or team. View top employees in any time dimension. Companies signed up for Recognize can enable this feature in their admin settings.</p>
            </div>
          </div>
          <div class="bucket" data-no-turbolink='true'>
            <div class="exp-feature-card">
              <div class="exp-feature-title">
                <%= image_tag "chrome/logo-mark-ios.png", class: "icon", alt: "Recognize icon" %>
                <h3><strong>Request a demo or sign up for free</strong><p>Learn more about the Recognize's employee engagement.</p></h3>
              </div>
              <p class="subtext">
                <%= link_to "Request a demo", contact_sales_path, class: "button button-highlight" %>
                <%= link_to "Sign up", sign_up_path, class: "button" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="movement">
      <div class="centered">
        <h2>Join the Recognition Movement</h2>
      </div>

      <div class="clearfix">
        <%= image_tag "pages/home-index/exp/movement.png", alt: "people and badges" %>

        <div class="content">
          <p class="tagline">Join the 20,000 people who stand for positivity and company culture. People drive your company. Do what you believe is the right thing for them.</p>
          <%= link_to "Join Now", sign_up_path, class: "button button-highlight" %>
        </div>
      </div>
    </section>

  </div>

</div>

<%= render :partial => 'footer' %>

app/views/home/pricing.html.erb
<section id="intro" class="animate-1 animate-hidden animate" data-no-turbolink="true">
  <div class="inner" data-no-turbolink="true">
    <h1 class="balance-text"><%= t(".title") %></h1>
    <p class="tagline balance-text"><%= t(".description") %></p>
    <%= link_to "Contact us & get started", contact_sales_path, class: "button button-big button-primary" %>
  </div>
  <%= render partial: "home/patterns/orange.svg" %>

</section>

<div id="points">
  <div class="prices clearfix">

    <% [{
          price: '$2',
          type: t(".users_month"),
          note: t(".user_description_html")
        },
        {
          price: '$0',
          type: t(".setup"),
          note: t(".remove_setup_cost", time: 5.weeks.from_now.strftime("%m/%d/%Y"))
        }].each_with_index do |package, i| %>

      <div class="price animate-<%= i+2 %> animate-hidden animate">
        <dl>
          <dd><%= package[:price] %></dd>
          <dt><%= package[:type] %></dt>
        </dl>
        <p class="balance-text subtle-text lead"><%= package[:note] %></p>
      </div>

    <% end %>

  </div>

  <div class="see-features-wrapper centered animate-1 animate-hidden animate">
    <h3>The pricing above includes all features</h3>
    <div class="table-outer">
      <table>
        <tr>
          <td class="lead subtle-text">Custom badges</td>
          <td class="lead subtle-text">Rewards</td>
          <td class="lead subtle-text">Leaderboards</td>
        </tr>
        <tr>
          <td class="lead subtle-text">Points</td>
          <td class="lead subtle-text">Departments</td>
          <td class="lead subtle-text">Tech Support</td>
        </tr>
        <tr>
          <td class="lead subtle-text">User Management</td>
          <td class="lead subtle-text">Yammer</td>
          <td class="lead subtle-text">Sharepoint</td>
        </tr>
        <tr>
          <td class="lead subtle-text">Mobile</td>
          <td class="lead subtle-text">Kiosk mode</td>
          <td class="lead subtle-text">Export data</td>
        </tr>
      </table>
    </div>

    <%= link_to "See the Complete List of Features", features_path, class: "button button-primary" %>
  </div>
</div>

app/views/home/proxy.html.erb
<!DOCTYPE HTML>
<div><%= Time.now.to_s %></div>
<script src="/assets/3p/xdomain.js"></script>
<script type="text/javascript">
    window.recognize.xdomain.masters({
      "https://*.yammer.com": "*"
    });  
</script>

app/views/home/robots.html.erb
<% if is_live_production_server? %>
Sitemap: https://www.recognizeapp.com.com/sitemap.xml.gz
<% else %>
User-Agent: *
Disallow: /
<% end %>