config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  use_doorkeeper

  resources :inbound_emails, only: [:create]
  resources :chat_threads
  resources :chat_messages
  
  namespace :api do
    namespace :v1 do
      Seahorse::Model.add_all_routes(self, exclude_rpc_routes: true)
    end
  end

  mount Api::Base => '/api'
  
  root :to => "home#index", :constraints => LoggedInConstraint.new(:logged_out_route)
  root :to => "recognitions#index", :constraints => LoggedInConstraint.new(:logged_in_route), as: :authenticated_root

  get '/proxy.html' => "home#proxy"
  
  # MISC ROUTES
  resources :password_resets, except: [:destroy]
  resources :support_emails, only: [:new, :create]

  get '/contact', to: 'support_emails#new', as: :contact
  get '/sales', to: 'support_emails#sales', as: :contact_sales

  # FILE ROUTES
  get '/extensions/recognize.xpi', to: 'files#firefox_extension'

  #ADMIN ROUTES
  get '/admin', to: 'admin/index#index', as: :admin, via: :get

  namespace :admin do
    get 'emails' => 'index#emails'
    get 'email' => 'index#email'
    get 'signup_requests' => 'index#signup_requests'
    get 'login' => "index#login"
    get 'graph' => 'index#graph'
    get 'paid_engagement' => 'index#paid_engagement'
    get 'analytics' => "index#analytics"
    post 'refresh_analytics' => "index#refresh_analytics"
    get 'queue' => "index#queue"
    post 'purge_failed_queue' => "index#purge_failed_queue"
    
    get '/login_as', to: "index#login_as"
    post "/login_as", to: "index#login_as"
    post '/clear_queue_task/:task', to: "index#clear_queue_task", as: :clear_queue_task

    # match '/enable_custom_badges' => 'index#enable_custom_badges', via: [:post]
    # get 'manage'
    resources :companies, only: [:show, :create], constraints: {:id => /[^\/]+/}  do
      member do
        post "enable_custom_badges"
        post "enable_admin_dashboard"
        post "enable_achievements"
        post "enable_theme"
        patch :add_users
        post :add_directors
        delete :remove_directors
      end
      resources :subscriptions, except: [:index] do
        member do
          patch :cancel
        end
      end
    end

    resources :recognitions, only: [:index]

    resources :users, only: [:index] do 
      collection do 
        get :search
      end
    end

    resources :badges, only: [:index, :show]
    resources :subscriptions, only: [:index]
    resources :coupons do
      collection do
        post :sync
      end
    end
  end
  
  #SESSION ROUTES
  get '/ping', to: 'user_sessions#ping'
  get '/login', to: 'user_sessions#new'
  get '/login/signin', to: 'user_sessions#create', :as => :signin, :id => 'Sign In'
  get '/logout', to: 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  
  #AUTHENTICATION ROUTES
  get '/auth/failure', to: 'authentications#failure', :as => :auth_failure
  get '/auth/:provider', to: 'authentications#create', :as => :remote_auth
  get '/auth/:provider/callback', to: 'authentications#create'

  # STATIC PATHS
  get "/getting-started", to: "home#getting_started", as: :getting_started
  get '/gamification', to: "home#gamification", as: :gamification
  get '/best-recognition-contest-2014', to: "home#contest", as: :contest
  get '/goto', to: "users#goto"
  get '/resend_verification_email', to: "password_resets#new", as: :resend_verification_email
  get '/home', to: "home#index", as: :marketing
  get '/sign-up', to: "home#sign_up", as: :sign_up
  get '/tour', to: "home#tour", as: :tour
  get '/engagement', to: "home#engagement", as: :engagement
  get '/analytics', to: "home#analytics", as: :analytics
  get '/customizations', to: "home#customizations", as: :customizations
  get '/pricing', to: "home#pricing", as: :pricing
  get '/features', to: "home#features", as: :features
  get '/about', to: "home#about", as: :about
  get '/yammer-integration', to: "home#extension", as: :extension
  get '/why-employee-recognition', to: "home#why", as: :why
  get '/case-study',to: "home#case_study", as: :case_study
  get '/privacy', to: "home#privacy_policy", as: :privacy_policy
  get '/terms', to: "home#terms_of_use", as: :terms_of_use
  get '/maintenance', to: "home#maintenance", :as => :maintenance
  get '/coworkers', to: "users#coworkers", as: :coworkers
  get '/help', to: redirect("http://recognize.zendesk.com"), :as => :help
  get '/upgrade/(:code)', to: "home#upgrade", as: :upgrade_promotion
  get "/distributed-workforce-infographic", to: "home#distributed_workforce_infographic", as: :distributed_workforce_infographic
  get "/year-in-review", to: "mailers#year_in_review"  
  get "/unsubscribe/:token", to: "users#unsubscribe", as: :unsubscribe
  get "/rewards", to: "home#rewards", as: :rewards
  get "/employee-recognition-awards", to: "home#awards", as: "awards"
  get "/office-365", to: "home#office365", as: :office365
  get "/mobile-employee-recognition", to: "home#mobile", as: :mobile
  get "/idp_check", to: "saml#idp_check"

  # COMPANY SCOPED ROUTES
  scope "/:network", constraints: {:network => /[^\/]+/} do
    constraints DomainConstraint.new do
      get "/" => "recognitions#index", as: "stream"
      get '/welcome', to: 'welcome#show', as: "welcome"
      put '/welcome/save_user_count', to: 'welcome#save_user_count', as: :save_user_count
  
      resources :subscriptions
      get '/upgrade', to: "subscriptions#new", as: :upgrade  
      get '/upgrade/(:code)', to: "subscriptions#new"

      # CORE RESOURCE ROUTES
      resource :company, only: [:show, :update] do
        resources :badges, only: [:new, :create, :destroy, :index, :show] do
          collection do
            patch :update_all
          end
        end

        get :accounts
        get :check_list
        get :reports
        get :recognitions
        post :update_privacy
        post :update_settings
        put :add_users
        post :resend_invitation_email
        patch :update_point_values
        patch :update_kiosk_mode_key
        patch :update_recognition_limits

        resources :rewards
        resource :saml_configuration

      end

      scope :company, module: :company_admin, as: :company_admin do
        resources :roles
        resources :nominations, only: [:index] do
          member do
            get :votes
            post :award
          end
        end
        resources :campaigns, only: [:show] do
          member do 
            post :archive
          end
        end
      end

      resources :departments
      resources :hall_of_fame
      resource :accounts, only: [:edit, :update]
      resources :redemptions, path: 'rewards'

      resources :teams do
        scope module: 'team_management' do
          resource :members, only: [:edit, :update]
          resource :managers, only: [:edit, :update]          
        end
        member do 
          get :nominations          
        end
      end

      resource :team_assignment, only: [:create, :destroy]

      resource :anniversaries , only: [] do
        collection do
          get :change_roles
          get :assign_role
          get :unassign_role
          get :add_user
          get :remove_user
        end
      end

      resources :email_settings
      # resources :invite

      #REPORTS ROUTES
      get "/reports", to: "reports#index", as: :reports
      get "/reports/users", to: "reports#users", as: :user_reports
      get "/reports/teams", to: "reports#teams", as: :team_reports
      get "/reports/top_users", to: "reports#top_users", as: :top_users_reports
      # get "/reports/:start_date", to: "reports#previous", as: :previous_report
      # get "/reports/badge/:badge_id/:start_date", to: "reports#badge_leaderboard", as: :badge_leaderboard

      # RECOGNITION ROUTES
      # skip show since that needs to be accessed unscoped
      # NOTE: must be above users to avoid dynamic matching
      resources :recognitions, except: [:show, :update, :destroy, :badge] do
        collection do
          post :recognize_instantly
          get :new_chromeless
        end
        member do
          patch :update, as: "update"
          delete :destroy, as: "destroy"
          put :toggle_privacy
        end
        resources :approvals, controller: "recognition_approvals", only: [:create, :destroy]
      end

      resource :identity_provider, path: "idp", only: [:show]
      resources :nominations, only: [:index, :new, :create] do
        collection do
          get :new_chromeless
        end
      end

      # USER ROUTES
      get "/users", to: "users#index", as: "users"
      resources :users, path: "", path_names: {new: "users/new"}, except:[:index, :create] do
        collection do
          get :invite
          get :get_suggested_yammer_users
          get :get_relevant_yammer_coworkers
          patch :send_invitations      
          patch :invite_from_yammer
        end
        member do
          patch :promote_to_admin
          patch :demote_from_admin
          patch :promote_to_executive
          patch :demote_from_executive
          patch :hide_welcome
          put :has_read_new_feature
          patch :upload_avatar
          patch :update_slug
          patch :revoke_oauth_token
          get :received_recognitions
          get :sent_recognitions
          get :nominations
        end

        # USER RECOGNITION ROUTES
        resources :recognitions, only: [] do
          collection do
            get :sent
            get :received
          end
        end

        resource :company_roles, only: [:create, :destroy], controller: :user_company_roles
      end

      resources :saml, only: :index do
        collection do
          get :sso
          post :acs
          get :metadata
          get :logout
          put :complete
        end
      end      

    end # end constraint
  end # end :domain scope

  # Allow showing a recognition to be unscoped 
  # since param is a guid
  # NOTE: this takes precedence over scoped routes

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < Admin::BaseController
  before_filter :set_company, except: [:index]

  def index
    @subscriptions = Subscription.all
    @mrr = Subscription.mrr_total
    @yrr = Subscription.yrr_total    
    @active_subscriptions = Subscription.active
    @canceled_subscriptions = Subscription.canceled
  end

  def edit
    @subscription = Subscription.find_by_id(params[:id])
    @user = @subscription.user
    @company = @subscription.company
  end

  def new
    if !company_has_subscription?
      @subscription = Subscription::Creator.initialize_subscription(@company, current_user)
    else
      flash[:error] = "A subscription already exists for that user's company"
      redirect_to "/admin/subscriptions"      
    end
  end

  def create
    @subscription = Subscription::Creator.create(@company, current_user, subscription_params)
    flash[:notice] = "Subscription created" unless @subscription.errors.present?
    respond_with @subscription, location: admin_subscriptions_path
  end

  def update
    @subscription = Subscription::Updater.update(@company, current_user, subscription_params)
    flash[:notice] = "Subscription updated" unless @subscription.errors.present?
    respond_with @subscription, location: admin_subscriptions_path
  end

  def cancel
    @company.subscription.cancel!
    flash[:notice] = "Subscription for #{@company.domain} has been cancelled"
    render js: "window.location = '#{admin_subscriptions_path}';"
  end

protected

  def company_has_subscription?
    @company.subscription.present?
  end

  def subscription_params
    params[:subscription].merge({skip_signature_validation: true})
  end

  def set_company
    @company = Company.where(domain: params[:company_id]).first    
    raise ActionController::RoutingError.new('Not Found') unless @company.present?
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  filter_access_to :show, :edit, :update, :destroy, attribute_check: true

  before_filter :prevent_multiple, only: [:new, :create]
  before_filter :checkout_verb, only: [:update]
  helper_method :coupon

  #the routing is kinda weird.  it works, but you're not really making a new subscription.  you're just being taken to an upgrade page
  def new
  end

  # {"utf8"=>"✓", "quantity"=>"500", "subscription"=>{"stripe_card_token"=>"[FILTERED]"}, "network"=>"poop.com"}
  def create
    @subscription = Subscription::Creator.create_and_purchase(current_user.company, current_user, params)

    # @subscription = current_user.create_subscription!(plan, coupon, subscription_params)
    redirect_path = @subscription.persisted? ?
                      subscription_path(@subscription, success: true) :
                      nil

    respond_with @subscription
  end

  def show
    @subscription = Subscription.find(params[:id])
    @next_invoice = @subscription.next_invoice
    @invoices = @subscription.invoices
    @show_contract = @subscription.contract_body.present?
  end
  
  def update
    @subscription = Subscription.find(params[:id])


    if @subscription.pending?
      @subscription.attributes = params[:subscription]
      @subscription.user_id = current_user.id

      @subscription.save_with_payment!
    else
      @subscription.update_card!(params[:subscription])
    end
    @next_invoice = @subscription.next_invoice
    @invoices = @subscription.invoices

    flash[:error] = "Could not #{checkout_verb} credit card" if @subscription.errors.present?
    flash[:notice] = "Subscription was successfully #{checkout_verb}d" unless @subscription.errors.present?

    respond_with @subscription, location: subscription_path(@subscription)
  end

  protected

  def checkout_verb
    @checkout_verb ||= @subscription.pending? ? "purchase" : "update"
  end
  helper_method :checkout_verb

  def plan
    Plan.find_by_name!("business200")
    # subscription_params.has_key?(:plan_id) ?
    #   Plan.find(subscription_params[:plan_id]) :
    #   params[:billing] || Plan.default(coupon)
  end
  
  def subscription_params
    params[:subscription] || {}
  end
  
  def coupon
    @coupon ||= Coupon.find_or_sync(params[:promotion] || params[:code] || params[:coupon])
  end
  
  def prevent_multiple
    subscription = (current_user.subscription || current_user.company.subscription)
    if subscription.present?
      redirect_to subscription_path(subscription)
    elsif current_user.subscribed_account?
      flash[:notice] = "You are already subscribed"
      redirect_to root_path
    end
  end
end

app/views/subscriptions/_cc_fields.html.erb
<%= render partial: "payment/cc" %>

<%= javascript_include_tag("https://js.stripe.com/v2/") %>
<%= javascript_include_tag("https://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.min.js") %>


<script type="text/javascript">
  $("head").append('<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY, id: "stripe-key" %>');
  window.R.paymentConfirmation();
</script>

app/views/subscriptions/_current_plan.html.erb
<hr class="hr">
<% if @subscription.user_count.present? %>
  <h3><%= @subscription.user_count%> users on the package</h3>
  <p>$<%= @subscription.unit_price%> / user / <%= @subscription.plan.interval_noun %></p>
  <hr>

<% else %>
  <% if @subscription.plan.present? && @subscription.plan.old_tiered_plan? %>
    <h3><%= @subscription.plan.package.humanize%> Package: <%= @subscription.plan.min_users%> - <%= @subscription.plan.max_users%> users</h3>
  <% else %>
    <h3><strong><%= number_to_currency(@subscription.amount, precision: 2)%> billed <%= @subscription.charge_interval%></strong></h3>
  <% end %>
<% end %>

<% if @subscription.plan.present? && @subscription.plan.old_tiered_plan? %>
  <p style="font-weight:bold">Total: $<%= number_with_precision(@subscription.recurring_cost, precision: 2)%> / <%= @subscription.plan.interval_noun %></p>
<% else %>
  <p style="font-weight:bold">Total: $<%= number_with_precision(@subscription.amount || @subscription.recurring_cost, precision: 2)%> / <%= @subscription.charge_interval_noun %></p>
<% end %>


<% if @subscription.plan.present? %>
  <h3>Next Invoice</h3>
  <% if @next_invoice %>
    <p><%= @next_invoice.date%> - $<%= number_with_precision(@next_invoice.amount_due, precision: 2) %></p>
  <% else %>
    <p>None</p>
  <% end %>

  <h3>Previous Invoice</h3>
  <ul>
    <% @subscription.invoices.each do |i| %>
      <li><%= i.date%> - $<%= number_with_precision(i.amount_due, precision: 2)%></li>
    <% end %>
  </ul>
<% end %>

<hr class="hr marginBottom40">

app/views/subscriptions/_invoice.html.erb
<div id="invoice">

  <% if @subscription.invoices.present? || !@subscription.credit_card? %>
    <%= render partial: "current_plan" %>
  <% else %>
    <%= render partial: "new_plan" %>
  <% end %>

  <% unless @subscription.pending? %>
    <h2>Update payment information</h2>
  <% end %>

  <div class="control-group">
    <label>
      <span class="label">Name on card</span>
      <input type="text" value="<%= @subscription.user.try(:full_name) || @current_user.full_name%>"/>
    </label>
    <label>
      <span class="label">Email</span>
      <input type="text" name="subscription[email]" value="<%= @subscription.email || current_user.email%>"/>
    </label>
  </div>
  <%= render partial: "subscriptions/cc_fields", locals: {hide_placeholders: true} if @subscription.credit_card? %>
  <div>
    <% submit_label = @subscription.pending? ? "Purchase" : "Update Card"%>
    <button id="submit-button" type="submit" class="button button-large button-primary form-loading-ignore"><%= submit_label%></button>
  </div>
</div>

app/views/subscriptions/_new_plan.html.erb
<h2>Invoice</h2>
<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <tbody>
      <tr>
        <td>Recurring cost</td>
        <td><%= @subscription.recurring_label %></td>
      </tr>

      <% @subscription.line_items.unbilled.each do |line_item| %>
        <tr>
          <td><%= line_item.description %></td>
          <td><%= number_to_currency(line_item.amount, precision: 2, locale: :en) %></td>
        </tr>
      <% end %>

      <tr class="total-row">
        <td>Total (billed now)</td>
        <td><%= number_to_currency(@subscription.total_with_unbilled_line_items, precision: 2, locale: :en) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/subscriptions/_payment_fields.html.erb
<div id="payment-wrapper">
    <span class="payment-errors"></span>
    <div class="form-vertical clearfix">
      <div class="form-column">
        <h4>Contact</h4>
        <div class="control-group">
          <label>
            <span class="label">Full Name</span>
            <input type="text" value="<%= @current_user.full_name%>"/>
          </label>
        </div>

      <div class="control-group">
        <label>
          <span class="label">Phone</span>
          <input type="number"/>
        </label>
      </div>
    </div><!-- end of left -->
    <div class="form-column">
      <div class="control-group">
        <label>
          <span class="label">Company Email *</span>
          <input id="payment-company-email" type="email" placeholder="email@company.com" required value="<%= current_user.email%>"/>
        </label>
      </div>
      <div class="hr-thick hr-space"></div>
      <h4>Credit Card</h4>
      <%= render partial: "cc_fields" %>

    </div> <!-- end of left -->

  </div><!-- end of vertical form -->

</div><!-- end of payment wrapper -->

app/views/subscriptions/_purchase_subscription.html.erb
<% if @show_contract %>
 <style type="text/css">
    @font-face {
      font-family: black_jack;
      src: url("/assets/black_jack-webfont.ttf") format("truetype"), url("/assets/black_jack-webfont.woff") format("woff"), url("/assets/black_jack-webfont.svg#black_jack") format("svg"), url("/assets/black_jack-webfont.eot");
    }
  </style>
<% end %>

<div class="payment-instructions">
  <h2>Payment Agreement <i class="subtle-text"><%= @company.name%></i></h2>
  <% if @subscription.pending? && @subscription.contract_title.present?   %>

    <h3>Steps</h3>
    <ol class="steps">
      <li class="step"><a href="#payment-form" class="animate-scroll">1. Review contract</a></li>
      <% if @show_contract %>
        <li class="step"><a href="#signature" class="animate-scroll">2. Sign contract</a></li>
      <% end %>
      <li class="step"><a href="#invoice" class="animate-scroll">3. Purchase</a></li>
    </ol>
  <% end %>
</div>

<div class="payment-callout">
  <% if !params[:success] && !@subscription.cancelled? %>
    <div>
    <h2 class="hidden"><%= "#{checkout_verb.capitalize} subscription" %></h2>
    <%= form_for @subscription, html: {id: "payment-form"} do |f|%>

      <%= render_flash(include_errors: @subscription) %>

      <% if @subscription.contract_title.present? %>
        <h1><%= @subscription.contract_title %></h1>
      <% end %>

      <% if @show_contract %>
        <div class="form-group contract-body">
          <%= @subscription.contract_body.html_safe %>
        </div>
      <% end %>

      <% if @show_contract %>
        <%= content_tag :div, class: "row-fluid marginVertical50" do %>
          <div class="row marginBottom40">
            <div class="span6">
              <div id="signature" class="form-material-group">
                <%= f.text_field :contract_signature, required: "required", readonly: @subscription.contract_signature.present? %>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label>Sign signature here</label>
              </div>
            </div>

            <div class="span6">
              <div id="date" class="form-material-group">
                <% value =  (@subscription.sign_date.blank? ? Time.now : @subscription.sign_date) %>
                <%= f.text_field :sign_date, required: "required", readonly: true, value: localize_datetime(value, :friendly)%>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label>Sign date</label>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <%= render partial: "invoice" %>
    <% end%>
    </div>
  <% end %>
</div>

app/views/subscriptions/_show.html.erb
<%= render partial: "invoice" %>

app/views/subscriptions/edit.html.erb
<%= render template: 'subscriptions/show' %>

app/views/subscriptions/new.html.erb
<div class="centered intro">
  <h1>Upgrade Recognize</h1>
  <p class="tagline marginBottom20">Retain and engage top staff through automated employee recognition.</p>
  <%= link_to "View the pricing", pricing_path, class: "button button-primary", data: {"no-turbolink": true} %>
</div>

<section class="instructions">
  <div class="row-fluid">
    <div class="span6">
      <%= image_tag "pages/subscriptions/upgrade-reasons.png", alt: "Align staff behind company initiatives, send official recognition from email, automatically share on Yammer, receive scheduled analytics reports." %>
    </div>
    <div class="span6">
      <div class="flex-centered">

        <%= form_for SupportEmail.new, remote: true, html: {data: {errorWrapper: "#trial-error-wrapper"}, class: "form-loading-ignore"} do |f| %>
          <div id="trial-error-wrapper"></div>
          <%= f.hidden_field :name, value: current_user.full_name %>
          <%= f.hidden_field :email, value: current_user.email %>
          <%= f.hidden_field :message, value: "upgrade" %>
          <%= f.hidden_field :phone, value: "n/a" %>

          <%= f.hidden_field :type, value: 'Sales' %>
          <button type="submit" class="button button-grande button-arrow">Notify us to get started</button>
        <% end %>


      </div>
    </div>
  </div>
</section>

<article>
  <%= render partial: "home/jay_quote" %>
</article>

app/views/subscriptions/show.html.erb
<% if params[:success] %>
  <h1 style="float:none;">Successfully Upgraded</h1>
<% end%>

<%= render partial: "purchase_subscription" %>